# Compose file reference: https://docs.docker.com/compose/compose-file/
version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    container_name: ${CONTAINER}
    hostname: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - ./:/home/db/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
