name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make test